import type { Metadata } from "next";
import "./globals.css";
import { Navbar, PageTransition, StairTransition } from "./components";


export const metadata: Metadata = {
  title: "Liliana | Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "./img/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar sections={['about','work','contact']}/>
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
