import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./components";
import PageTransition from "./components/PageTransition";
import StairTransition from "./components/StairTransition";

export const metadata: Metadata = {
  title: "Liliana | Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "./img/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
