import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Liliana | Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: './img/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
