import type { Metadata } from "next";
import {
  AboutComponent,
  ContactComponent,
  Hero,
  WorksComponent,
  StarsCanvas,
  Navbar,
} from "./components";
import { StarsBackground } from "./components/ui/stars-background";
import BlobPage from "./components/Blob";

export const metadata: Metadata = {
  title: "Liliana | Portfolio",
  description: "Generated by Liliana Forero",
  icons: {
    icon: "./img/logo.png",
  },
};

export default function Home() {
  return (
    <>
      <Navbar sections={["about", "work", "contact"]} />
      <div className="relative z-0 bg-primary select-none">
        <Hero />
        <AboutComponent />
        <WorksComponent />
        <ContactComponent />
        <StarsBackground />
      </div>
    </>
  );
}
