import type { Metadata } from "next";
import {
  AboutComponent,
  ContactComponent,
  Hero,
  WorksComponent,
  StarsCanvas,
  Navbar,
} from "./components";

export const metadata: Metadata = {
  title: "Liliana | Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "./img/logo.png",
  },
};

export default function Home() {
  return (
    <>
      <Navbar sections={["about", "work", "contact"]} />
      <div className="relative z-0 bg-primary select-none">
        <div className=" bg-cover bg-no-repeat bg-center">
          <Hero />
        </div>
        <AboutComponent />
        <WorksComponent />
        <div className="relative z-0">
          <ContactComponent />
          <StarsCanvas />
        </div>
      </div>
    </>
  );
}
